export const appConstants = {
  // HOME
  HOME_UPDATE_LIST: 'HOME_UPDATE_LIST',

  // AGENCIES
  AGENCIES_UPDATE_LIST: 'AGENCIES_UPDATE_LIST',
  AGENCIES_UPDATE_DETAILS: 'AGENCIES_UPDATE_DETAILS',
  AGENCIES_LOAD_DETAILS: 'AGENCIES_LOAD_DETAILS',
  AGENCIES_LOAD_PROFILES: 'AGENCIES_LOAD_PROFILES',

  // EMPLOYEES
  EMPLOYEES_UPDATE_LIST: 'EMPLOYEES_UPDATE_LIST',

  // AIRLINES
  AIRLINES_UPDATE_LIST: 'AIRLINES_UPDATE_LIST',

  //DONE
  MOOBLAB: 'MOOBLAB'
};
