export const appConstants = {
  // HOME
  HOME_UPDATE_LIST: 'HOME_UPDATE_LIST',

  // CONTACTS
  CONTACTS_UPDATE_LIST: 'CONTACTS_UPDATE_LIST',
  CONTACTS_GROUPS_UPDATE_LIST: 'CONTACTS_GROUPS_UPDATE_LIST',

  // GROUPS
  GROUPS_UPDATE_LIST: 'GROUPS_UPDATE_LIST',

  //DONE
  MOOBLAB: 'MOOBLAB'
};
